server:
  port: 11000
spring:
  application:
    name: rocketmq-consumer
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

rocketmq:
  # mq的nameserver地址
  name-server: 47.94.140.208:9876
  producer:
    # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    group: rocketmq-consumer
    # 是否开启自动配置
    max-message-size: 4194304
    isOnOff: on
    compress-message-body-threshold: 4096
    # 发送消息超时时间，默认 3000
    send-message-timeout: 3000
    retry-times-when-send-async-failed: 0
    retry-next-server: true
    retry-times-when-send-failed: 2
